Repository pawarspeaks/TechNexus, pull requests merged in 2023-10, with the labels that each got.

#3 added an offline and online events
  images/cosmoCode.jpg
  images/cssBattles.jpg
  images/innerve.jpg
  images/kinetic.jpg
  offline-events.html
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#2 capatilized contact and added a online event
  index.html
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#5 Added two offline events #1
  images/cyberx.png
  offline-events.html
Labels: hacktoberfest, hacktoberfest2023

#6 Added one online and two offline hackathons
  images/bharat_yatra.jpg
  images/eduspark.webp
  images/fpga.webp
  offline-events.html
  virtual-events.html
Labels: good first issue, hacktoberfest, hacktoberfest2023

#4 added a virtual event
  images/Brizy-no-code.jpeg
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#7 added new virtual event
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#8 ICPC Online event 2023
  images/foundationlogo.png
  images/gfgjobathon.jpeg
  offline-events.html
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#10 CND Event Pune
  images/cnd.png
  offline-events.html
Labels: hacktoberfest, hacktoberfest2023

#13 Added new virtual event-Intellect Global Hackathon
  images/IntellectGlobalHackathon.png
  images/hackwithinfy.png
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#14 Added an offline event
  images/Reva_Hack.webp
  offline-events.html
Labels: hacktoberfest, hacktoberfest2023

#20 Added Saptech Event
  images/sapteched2023virtual.png
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#17 Added Functionality to the Anchor Tag
  images/reg-og.png
  index.html
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#21 Feat : About us section
  contributors.css
  contributors.html
  style.css
Labels: hacktoberfest, hacktoberfest2023

#24 Added an event in virtual events
  images/allin.jpg
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#25 Issue no. #19 [FIXED] Favicon is added in the site.
  Favicon/android-chrome-192x192.png
  Favicon/android-chrome-512x512.png
  Favicon/apple-touch-icon.png
  Favicon/favicon-16x16.png
  Favicon/favicon-32x32.png
  Favicon/favicon.ico
  Favicon/site.webmanifest
  index.html
Labels: hacktoberfest, hacktoberfest2023

#26 Issue No. #18 [FIXED] Copyright year added in the footer section.
  contributors.html
  copyrightYear.js
  index.html
  offline-events.html
  style.css
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#29 Added offline event
  offline-events.html
Labels: hacktoberfest, hacktoberfest2023

#30 Made index.html responsive
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest2023

#33 fixes consistency of style among diff pages
  contributors.html
  offline-events.html
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#34 added Constellation- A Chainlink hackathon
  images/constellation.png
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#35 Issue No. #31 [FIXED] Favicon added in Offline Events, Online Events, Our team and contact page.
  contributors.html
  offline-events.html
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023

#40 Better cards design
  static/css/include.css
Labels: enhancement, hacktoberfest, hacktoberfest2023

#43 Update offline-events in Amity Noida Google Cloud Study Jams: Communi…
  offline-events.html
Labels: hacktoberfest, hacktoberfest2023

#45 Update offline-events.html
  images/AWS-cloud-clubs.png
  images/bharat_yatra.jpg
  images/cnd.png
  images/cosmoCode.jpg
  images/cssBattles.jpg
  images/fpga.webp
  images/hack-hive.png
  images/hack-the-moutain.png
  offline-events.html
Labels: hacktoberfest, hacktoberfest2023

#46 Removal of all the completed virtual events and their assets from the repository & website
  images/Brizy-no-code.jpeg
  images/EY-techathon.png
  images/Hack-unicorn2.0.png
  images/allin.jpg
  images/codegeist-unleased.png
  images/eduspark.webp
  images/gfgjobathon.jpeg
  images/innerve.jpg
  images/kinetic.jpg
  images/reg-og.png
  offline-events.html
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023, HACKTOBERFEST-ACCEPTED\

#47 Added a new event: .NET Conference MIET
  images/MIET-DotNet-Conf.png
  offline-events.html
Labels: hacktoberfest, hacktoberfest2023, HACKTOBERFEST-ACCEPTED\

#48 Added a virtual even to the TechNexus: cruXipher by BITS Pilani
  images/cruXipher.png
  virtual-events.html
Labels: hacktoberfest, hacktoberfest2023, HACKTOBERFEST-ACCEPTED
