Repository pawarspeaks/TechNexus, pull requests merged in 2024-10, with the labels that each got.

#56 contribution for hacktoberfest: added a new upcoming technical event
  public/images/onlineEvents/ai_driven_india_hackathon.png
  src/data/onlineEventsData.json
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED, hacktoberfest2024

#68 Adding Favicon and Title
  index.html
  public/images/Favicon/android-chrome-192x192.png
  public/images/Favicon/android-chrome-512x512.png
  public/images/Favicon/apple-touch-icon.png
  public/images/Favicon/favicon-16x16.png
  public/images/Favicon/favicon-32x32.png
  public/images/Favicon/favicon-48x48.png
  public/images/Favicon/favicon.ico
  public/images/Favicon/favicon.svg
  public/images/Favicon/site.webmanifest
  public/images/Favicon/web-app-manifest-192x192.png
  public/images/Favicon/web-app-manifest-512x512.png
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#72 chore: adding technical events
  public/images/onlineEvents/AIfor Impact APAC Hackathon.png
  public/images/onlineEvents/GHCI 24 Hackathon For Girls.png
  public/images/onlineEvents/Namma Yatri Software Development Engineer Hiring Challenge 2024.png
  public/images/onlineEvents/Sparkplug -  Summer Internship 2025.png
  public/images/onlineEvents/ULIP Logixtics Hackathon 2.0.png
  src/data/onlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#66 responsive
  src/index.css
Labels: enhancement, hacktoberfest, hacktoberfest2024

#75 Added two offline and one online upcoming event.
  public/images/offlineEvents/devcon.jpg
  public/images/offlineEvents/opensource.jpg
  public/images/onlineEvents/hackathonai.jpg
  src/data/offlineEventsData.json
  src/data/onlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#65 FIX#59
  package-lock.json
  package.json
  src/App.jsx
  src/Styles/Button.js
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/ScrollToTopButton.jsx
  src/main.jsx
  src/pages/Contact.jsx
  tailwind.config.js
Labels: hacktoberfest, hacktoberfest2024

#78 Added 7 upcoming offline events
  public/images/offlineEvents/bengalurutechsummit.png
  public/images/offlineEvents/fintechindia.png
  public/images/offlineEvents/hackcbs.png
  public/images/offlineEvents/indiafoss.png
  public/images/offlineEvents/iotindiaexpo.png
  public/images/offlineEvents/mobileindiaexpo.png
  public/images/offlineEvents/nasscomtl2025.png
  src/data/offlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#89 Issue #86 - Filter enhancement in the Event List Page
  src/components/EventCard.jsx
  src/components/EventList.jsx
  src/components/FilterForm.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024

#101 Feature Request: Add Hamburger Menu for Mobile Devices and Improve Responsiveness
  src/HamburgerMenu.css
  src/components/Header.jsx
  src/components/HomePage.jsx
  src/index.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#102 Removed id dependency and sort by date is added
  index.html
  src/components/EventList.jsx
  src/components/FilterForm.jsx
Labels: good first issue, hacktoberfest, hacktoberfest2024

#104 Updated offlineEventsData.json
  public/images/offlineEvents/g81.jpg
  src/data/offlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#117 solved #116 how it works card shadow changed on hover
  src/components/HomePage.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024

#107 [feat] : Add an offline tech event
  public/images/offlineEvents/latitude59.png
  src/data/offlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#119 Icons error fixed in the footer by adding fontawesome.
  package-lock.json
  package.json
  src/App.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024

#99 New online Event
  public/images/onlineEvents/670e3ca72f94e_unstops-got-latent.webp
  public/images/onlineEvents/MongoDB-aws.png
  public/images/onlineEvents/Screenshot 2024-10-16 012348.png
  public/images/onlineEvents/b498e93f8a-asian_paints_banner.jpg
  public/images/onlineEvents/full_width (1).png
  public/images/onlineEvents/gsk2024.webp
  src/data/onlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#70 Implementation of Contact Page
  src/App.jsx
  src/components/ContactForm.jsx
  src/components/Footer.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024

#124 Added new event details.
  public/images/offlineEvents/thumb6709106705a7d.webp
  src/data/offlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#126 Added Dropdown for location field in offline events page. The locations are fetched from the Offline events Json file
  src/components/FilterForm.jsx
Labels: hacktoberfest, hacktoberfest2024

#108 Added New Offline Events
  public/images/offlineEvents/DevFest 2024 Gurugram.png
  public/images/offlineEvents/DevFest Noida 2024.png
  public/images/offlineEvents/Innova 2024 Delhi NCR.jpg
  public/images/offlineEvents/TensorFlow User Group Delhi.png
  src/data/offlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#128 Issue#127
  package-lock.json
  package.json
  public/images/offlineEvents/ai_driven_india_hackathon.png
  src/App.jsx
  src/components/CreateEvent.css
  src/components/CreateEvent.jsx
  src/components/EventCard.jsx
  src/components/EventList.jsx
  src/services/eventsservice.js
Labels: enhancement, hacktoberfest, hacktoberfest2024

#129 New offline event added
  public/images/offlineEvents/expo.jpg
  src/data/offlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#114 fixed button misalignment #110
  src/components/EventCard.jsx
  src/components/Footer.jsx
Labels: good first issue, hacktoberfest, hacktoberfest2024

#130 Fix for issue #109
  src/components/HomePage.jsx
Labels: hacktoberfest, hacktoberfest2024

#79 footer enhancement
  package-lock.json
  package.json
  src/components/Footer.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024

#136 added upcoming online technical events
  public/images/onlineEvents/EYtechathon.jpg
  public/images/onlineEvents/SamsungEdge.jpg
  src/data/onlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#125 chore: added new online/offline events
  public/images/offlineEvents/IBW-04-05-dec-thur-10-AM-offline-event.png
  public/images/offlineEvents/IBW-20-oct-offline-event-8-30-PM.png
  public/images/offlineEvents/devworkshop.png
  public/images/offlineEvents/road-to-devcon-31st-oct-thur-1-PM.png
  public/images/offlineEvents/sigma-sync-sprint-20-oct-offline-event-7-oct-04-PM.png
  public/images/onlineEvents/awscostexplorer.png
  public/images/onlineEvents/finetuning.png
  public/images/onlineEvents/githubcopilot.png
  public/images/onlineEvents/onlineEvent-10-Nov-6-PM.png
  public/images/onlineEvents/pythonpune.png
  src/data/offlineEventsData.json
  src/data/onlineEventsData.json
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED, hacktoberfest2024

#134 Added TechNexus event
  public/images/offlineEvents/AI-Vision-Conclave.png
  public/images/offlineEvents/BLR-TECH-SUMMIT.png
  public/images/offlineEvents/ET-TECH-X.png
  public/images/offlineEvents/RT-SPECTRUM-2025.jpg
  public/images/offlineEvents/leverage.png
  src/data/offlineEventsData.json
Labels: hacktoberfest, hacktoberfest2024

#137 fix: reset filter issue
  src/components/EventList.jsx
Labels: hacktoberfest, hacktoberfest2024
